; generated by c_compiler for the E0C6S46
; variables: wert@0x40, name1@0x41, zaehler@0x44, zustand@0x45, p_x@0x46, p_y@0x47, u_lo@0x48
; ---- main @ 0x000 ----
    .org 0x000
main:
    LD X, 0x40
    LD MX, 0x3
    LD X, 0x44
    LD MX, 0xC
    LD X, 0x45
    LD MX, 0x6
    LD X, 0x46
    LD MX, 0x4
    LD X, 0x47
    LD MX, 0x9
    LD X, 0x48
    LD MX, 0x7
    LD X, 0x40
    LD A, MX
    LD X, 0x3C
    LD MX, A
    PSET 0x1
    CALL __print_dec
    LD X, 0x44
    LD A, MX
    LD X, 0x3C
    LD MX, A
    PSET 0x1
    CALL __print_dec
    LD X, 0x45
    LD A, MX
    LD X, 0x3C
    LD MX, A
    PSET 0x1
    CALL __print_dec
    LD X, 0x46
    LD A, MX
    LD X, 0x3C
    LD MX, A
    PSET 0x1
    CALL __print_dec
    LD X, 0x47
    LD A, MX
    LD X, 0x3C
    LD MX, A
    PSET 0x1
    CALL __print_dec
    LD X, 0x48
    LD A, MX
    LD X, 0x3C
    LD MX, A
    PSET 0x1
    CALL __print_dec
    LD A, 0x2
    LD X, 0x3C
    LD MX, A
    PSET 0x1
    CALL __print_dec
    LD A, 0x1
    LD X, 0x3C
    LD MX, A
    PSET 0x1
    CALL __print_dec
    LD A, 0x1
    LD X, 0x3C
    LD MX, A
    PSET 0x1
    CALL __print_dec
    LD A, 0x3
    LD X, 0x3C
    LD MX, A
    PSET 0x1
    CALL __print_dec
    LD X, 0x40
    LD MX, 0x0
W1:
    LD X, 0x40
    LD A, MX
    LD B, 0xF
    SUB A, B
    JP NC, W2
    LD X, 0x40
    ADD MX, 0x1
    JP W1
W2:
W3:
    JP W3
W4:
    RET

    .org 0x110   ; runtime library
; ---- __dbg_trigger @ 0x110 ----
    .org 0x110

__dbg_trigger:
    LD A, 0xF
    LD XP, A
    LD X, 0x0E
    LD A, 0x1
    LD MX, A
    LD A, 0x0
    LD XP, A
    RET
; ---- __print_dec @ 0x11A ----
    .org 0x11A

__print_dec:
    LD X, 0x3C
    LD A, MX
    LD X, 0xC0
    CP A, 0xA
    JP C, pd_one
    LD MX, 0x1
    INC X
    LD A, 0x3
    LD MX, A
    INC X
    LD X, 0x3C
    LD A, MX
    LD B, 0xA
    SUB A, B
    LD X, 0xC2
    LD MX, A
    INC X
    LD A, 0x3
    LD MX, A
    INC X
    LD MX, 0x0
    INC X
    LD MX, 0x0
    JP __dbg_trigger
pd_one:
    LD MX, A
    INC X
    LD A, 0x3
    LD MX, A
    INC X
    LD MX, 0x0
    INC X
    LD MX, 0x0
    JP __dbg_trigger
