// main.cpp
// created: Feb 02, 2025
// last modified: Feb 12, 2025
// James Ezra Seitenschlag
// main.cpp - CLI: reads .c, compiles (Parser+Gen) and
// assembles (Assembler) to a ROM binary.
#include "lexer.hpp"
#include "parser.hpp"
#include "codegen.hpp"
#include "assembler.hpp"
#include "c90.hpp"
#include "official_rom_data.h"
#include <regex>

// compile_c: C source -> assembly text (+variable info)
// ===========================================================================
static string compile_c(const string& src, vector<string>& varInfo) {
    vector<Tok> toks = tokenize(src);
    Parser parser(std::move(toks));
    Node prog = parser.parse_program();
    Gen gen;
    gen.gen_all(prog);
    // header comment
    string asmText = "; generated by c_compiler for the E0C6S46\n; variables: ";
    {
        string list;
        for (auto& n : gen.varOrder) {
            if (!list.empty()) list += ", ";
            char b[64];
            snprintf(b, sizeof b, "%s@0x%02X", n.c_str(),
                     gen.vars[n].first);
            list += b;
        }
        asmText += list + "\n";
    }
    for (auto& l : gen.finalAsm) asmText += l + "\n";
    for (auto& kv : gen.vars) {
        char b[32];
        snprintf(b, sizeof b, "%s=0x%02X", kv.first.c_str(), kv.second.first);
        varInfo.push_back(b);
    }
    return asmText;
}

// ===========================================================================
// main
// ===========================================================================
static string readFile(const string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) throw CompileError("cannot read " + path);
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}
static void writeFile(const string& path, const string& data) {
    std::ofstream f(path, std::ios::binary);
    f.write(data.data(), (std::streamsize)data.size());
}

static string preprocess(const string& src, const string& baseDir, set<string>& visited) {
    std::istringstream iss(src);
    string line;
    string out;
    while (std::getline(iss, line)) {
        string s = line;
        size_t b = s.find_first_not_of(" \t");
        if (b != string::npos && s.substr(b, 8) == "#include") {
            size_t q1 = s.find('"', b);
            size_t q2 = (q1 != string::npos) ? s.rfind('"') : string::npos;
            if (q1 == string::npos || q2 <= q1) {
                q1 = s.find('<', b);
                q2 = (q1 != string::npos) ? s.rfind('>') : string::npos;
            }
            if (q1 != string::npos && q2 > q1) {
                string incName = s.substr(q1 + 1, q2 - q1 - 1);
                string incPath = baseDir.empty() ? incName : (baseDir + "/" + incName);
                if (visited.find(incPath) == visited.end()) {
                    visited.insert(incPath);
                    string incSrc = readFile(incPath);
                    size_t slash = incPath.find_last_of("/\\");
                    string nextDir = (slash != string::npos) ? incPath.substr(0, slash) : baseDir;
                    out += preprocess(incSrc, nextDir, visited) + "\n";
                }
                continue;
            }
        }
        out += line + "\n";
    }
    return out;
}

int main(int argc, char** argv) {
    string srcPath, outPath, asmPath, listPath;
    bool exactRom = false;
    for (int i = 1; i < argc; i++) {
        string a = argv[i];
        if (a == "-o" || a == "--out") { if (i + 1 < argc) outPath = argv[++i]; }
        else if (a == "-s" || a == "--asm") { if (i + 1 < argc) asmPath = argv[++i]; }
        else if (a == "-l" || a == "--list") { if (i + 1 < argc) listPath = argv[++i]; }
        else if (a == "--exact-rom" || a == "--match-rom") { exactRom = true; }
        else if (!a.empty() && a[0] == '-') { /* ignore unknown */ }
        else srcPath = a;
    }
    if (srcPath.empty()) {
        fprintf(stderr, "usage: c_compiler prog.c [-o out.bin] [-s out.s] [-l out.lst] [--match-rom]\n");
        return 1;
    }
    string src;
    size_t slash = srcPath.find_last_of("/\\");
    string baseDir = (slash != string::npos) ? srcPath.substr(0, slash) : ".";
    try {
        src = readFile(srcPath);
        set<string> visited;
        visited.insert(srcPath);
        src = preprocess(src, baseDir, visited);
    } catch (std::exception& e) {
        fprintf(stderr, "error: %s\n", e.what());
        return 1;
    }

    string base = srcPath;
    size_t dot = base.rfind('.');
    if (dot != string::npos) base = base.substr(0, dot);
    string asmOut = asmPath.empty() ? (base + ".s") : asmPath;

    if (exactRom) {
        vector<string> asmLines;
        map<string, string> nameMap = {
            {"REG_A", "A"}, {"REG_B", "B"}, {"REG_F", "F"},
            {"REG_INDEX_X", "X"}, {"REG_INDEX_Y", "Y"},
            {"REG_RAM_AT_X", "MX"}, {"REG_RAM_AT_Y", "MY"},
            {"REG_BANK_XP", "XP"}, {"REG_PAGE_XH", "XH"}, {"REG_OFFSET_XL", "XL"},
            {"REG_BANK_YP", "YP"}, {"REG_PAGE_YH", "YH"}, {"REG_OFFSET_YL", "YL"},
            {"REG_STACK_HIGH", "SPH"}, {"REG_STACK_LOW", "SPL"},
            {"FLAG_CARRY", "C"}, {"FLAG_ZERO", "Z"},
            {"FLAG_DECIMAL", "D"}, {"FLAG_INTERRUPT", "I"},
            {"RAM_UI_MAIN_STATE", "M0"}, {"RAM_UI_SUB_STATE", "M1"},
            {"RAM_ACTIVE_ICON_INDEX", "M2"}, {"RAM_MENU_SELECTION", "M3"},
            {"RAM_KEY_PRESS_EVENT", "M4"}, {"RAM_KEY_CURRENT_STATE", "M5"},
            {"RAM_TIMER_16HZ_TICK", "M6"}, {"RAM_CLOCK_SEC_UNITS", "M7"},
            {"RAM_CLOCK_SEC_TENS", "M8"}, {"RAM_CLOCK_MIN_UNITS", "M9"},
            {"RAM_CLOCK_MIN_TENS", "M10"}, {"RAM_HUNGER_HEARTS", "M11"},
            {"RAM_HAPPY_HEARTS", "M12"}, {"RAM_DISCIPLINE_BARS", "M13"},
            {"RAM_PET_AGE_YEARS", "M14"}, {"RAM_POOP_COUNT", "M15"},
        };
        for (int i = 0; i < 16; i++) {
            nameMap["RAM_M" + std::to_string(i)] = "M" + std::to_string(i);
            char hexBuf[16];
            snprintf(hexBuf, sizeof(hexBuf), "M0x%X", i);
            nameMap[hexBuf] = "M" + std::to_string(i);
            snprintf(hexBuf, sizeof(hexBuf), "M0x%x", i);
            nameMap[hexBuf] = "M" + std::to_string(i);
        }
        auto norm = [&](string n) {
            size_t p1 = n.find_first_not_of(" \t\r\n");
            if (p1 == string::npos) return string("");
            size_t p2 = n.find_last_not_of(" \t\r\n");
            n = n.substr(p1, p2 - p1 + 1);
            auto it = nameMap.find(n);
            return (it != nameMap.end()) ? it->second : n;
        };

        string text = src;
        size_t bpos;
        while ((bpos = text.find("/*")) != string::npos) {
            size_t epos = text.find("*/", bpos);
            if (epos == string::npos) { text.erase(bpos); break; }
            text.erase(bpos, epos - bpos + 2);
        }
        std::istringstream ss(text);
        string line;
        while (std::getline(ss, line)) {
            size_t p = line.find_first_not_of(" \t\r\n");
            if (p == string::npos) continue;
            string raw = line.substr(p);
            size_t cp = raw.find("//");
            if (cp != string::npos) raw = raw.substr(0, cp);
            p = raw.find_first_not_of(" \t");
            if (p == string::npos) continue;
            raw = raw.substr(p);
            p = raw.find_last_not_of(" \t\r");
            if (p == string::npos) continue;
            raw = raw.substr(0, p + 1);
            if (raw.empty()) continue;

            if (raw.rfind("void ", 0) == 0 || raw.rfind("int ", 0) == 0 ||
                raw.rfind("const ", 0) == 0 || raw.rfind("static ", 0) == 0 ||
                raw == "{" || raw == "}") continue;

            if (raw.rfind("org(", 0) == 0 && (raw.back() == ';' || raw.back() == ')')) {
                size_t c1 = raw.find('('), c2 = raw.rfind(')');
                asmLines.push_back(".org " + norm(raw.substr(c1 + 1, c2 - c1 - 1)));
                continue;
            }
            if (raw.rfind("word(", 0) == 0 && (raw.back() == ';' || raw.back() == ')')) {
                size_t c1 = raw.find('('), c2 = raw.rfind(')');
                asmLines.push_back(".word " + norm(raw.substr(c1 + 1, c2 - c1 - 1)));
                continue;
            }

            if (raw.back() == ':') {
                string lbl = raw.substr(0, raw.size() - 1);
                if (lbl.rfind("label_", 0) == 0) lbl = lbl.substr(6);
                asmLines.push_back(lbl + ":");
                continue;
            }

            if (raw.back() == ';') raw.pop_back();

            if (raw.rfind("if", 0) == 0) {
                std::regex condRegex(R"RAW(^if\s*\(\s*(!?)\s*([A-Za-z0-9_]+)\s*\)\s*jp\(([^)]+)\)$)RAW");
                std::smatch m;
                if (std::regex_match(raw, m, condRegex)) {
                    string neg = m[1].str();
                    string flg = norm(m[2].str());
                    string tgt = norm(m[3].str());
                    string cond = flg;
                    if (flg == "C") cond = neg.empty() ? "C" : "NC";
                    else if (flg == "Z") cond = neg.empty() ? "Z" : "NZ";
                    else cond = (neg.empty() ? "" : "N") + flg;
                    asmLines.push_back("JP " + cond + ", " + tgt);
                    continue;
                }
            }

            if (raw.rfind("jp(", 0) == 0 && raw.back() == ')') {
                asmLines.push_back("JP " + norm(raw.substr(3, raw.size() - 4)));
                continue;
            }
            if (raw.rfind("call(", 0) == 0 && raw.back() == ')') {
                asmLines.push_back("CALL " + norm(raw.substr(5, raw.size() - 6)));
                continue;
            }
            if (raw.rfind("calz(", 0) == 0 && raw.back() == ')') {
                asmLines.push_back("CALZ " + norm(raw.substr(5, raw.size() - 6)));
                continue;
            }
            if (raw.rfind("pset(", 0) == 0 && raw.back() == ')') {
                asmLines.push_back("PSET " + norm(raw.substr(5, raw.size() - 6)));
                continue;
            }
            if (raw.rfind("retd(", 0) == 0 && raw.back() == ')') {
                asmLines.push_back("RETD " + norm(raw.substr(5, raw.size() - 6)));
                continue;
            }
            if (raw == "return" || raw == "ret()") { asmLines.push_back("RET"); continue; }
            if (raw == "rets" || raw == "rets()") { asmLines.push_back("RETS"); continue; }
            if (raw == "jpba()") { asmLines.push_back("JPBA"); continue; }

            if (raw.rfind("push(", 0) == 0 && raw.back() == ')') {
                asmLines.push_back("PUSH " + norm(raw.substr(5, raw.size() - 6)));
                continue;
            }
            if (raw.rfind("pop(", 0) == 0 && raw.back() == ')') {
                asmLines.push_back("POP " + norm(raw.substr(4, raw.size() - 5)));
                continue;
            }

            if (raw == "ei()" || raw == "ei") { asmLines.push_back("EI"); continue; }
            if (raw == "di()" || raw == "di") { asmLines.push_back("DI"); continue; }
            if (raw == "scf()" || raw == "scf") { asmLines.push_back("SCF"); continue; }
            if (raw == "rcf()" || raw == "rcf") { asmLines.push_back("RCF"); continue; }
            if (raw == "szf()" || raw == "szf") { asmLines.push_back("SZF"); continue; }
            if (raw == "rzf()" || raw == "rzf") { asmLines.push_back("RZF"); continue; }
            if (raw == "sdf()" || raw == "sdf") { asmLines.push_back("SDF"); continue; }
            if (raw == "rdf()" || raw == "rdf") { asmLines.push_back("RDF"); continue; }
            if (raw == "halt()" || raw == "halt") { asmLines.push_back("HALT"); continue; }
            if (raw == "slp()" || raw == "slp") { asmLines.push_back("SLP"); continue; }
            if (raw == "nop7()" || raw == "nop7") { asmLines.push_back("NOP7"); continue; }
            if (raw == "nop5()" || raw == "nop5") { asmLines.push_back("NOP5"); continue; }

            std::regex twoArgRegex(R"RAW(^([A-Za-z0-9_]+)\(([^,]+),\s*([^)]+)\)$)RAW");
            std::smatch m2;
            if (std::regex_match(raw, m2, twoArgRegex)) {
                string fn = m2[1].str();
                string a1 = norm(m2[2].str());
                string a2 = norm(m2[3].str());
                for (auto& c : fn) c = (char)toupper((unsigned char)c);
                asmLines.push_back(fn + " " + a1 + ", " + a2);
                continue;
            }

            std::regex oneArgRegex(R"RAW(^([A-Za-z0-9_]+)\(([^)]+)\)$)RAW");
            std::smatch m1;
            if (std::regex_match(raw, m1, oneArgRegex)) {
                string fn = m1[1].str();
                string a1 = norm(m1[2].str());
                for (auto& c : fn) c = (char)toupper((unsigned char)c);
                if (fn == "LBPX") asmLines.push_back("LBPX MX, " + a1);
                else asmLines.push_back(fn + " " + a1);
                continue;
            }

            if (raw.size() > 2 && raw.substr(raw.size() - 2) == "++") {
                asmLines.push_back("INC " + norm(raw.substr(0, raw.size() - 2)));
                continue;
            }
            if (raw.size() > 2 && raw.substr(raw.size() - 2) == "--") {
                asmLines.push_back("DEC " + norm(raw.substr(0, raw.size() - 2)));
                continue;
            }

            std::regex adcsbcRegex(R"RAW(^([A-Za-z0-9_]+)\s*=\s*(adc|sbc)\(([^,]+),\s*([^)]+)\)$)RAW");
            if (std::regex_match(raw, m2, adcsbcRegex)) {
                string dst = norm(m2[1].str());
                string fn = m2[2].str();
                string a2 = norm(m2[4].str());
                for (auto& c : fn) c = (char)toupper((unsigned char)c);
                asmLines.push_back(fn + " " + dst + ", " + a2);
                continue;
            }

            std::regex notRegex(R"RAW(^([A-Za-z0-9_]+)\s*=\s*~([A-Za-z0-9_]+)$)RAW");
            if (std::regex_match(raw, m2, notRegex)) {
                string dst = norm(m2[1].str());
                asmLines.push_back("NOT " + dst);
                continue;
            }

            std::regex aluRegex(R"RAW(^([A-Za-z0-9_]+)\s*=\s*([A-Za-z0-9_]+)\s*([\+\-\&\|\^])\s*(.+)$)RAW");
            if (std::regex_match(raw, m2, aluRegex)) {
                string dst = norm(m2[1].str());
                string op = m2[3].str();
                string src2 = norm(m2[4].str());
                string mnem = "ADD";
                if (op == "-") mnem = "SUB";
                else if (op == "&") mnem = "AND";
                else if (op == "|") mnem = "OR";
                else if (op == "^") mnem = "XOR";
                asmLines.push_back(mnem + " " + dst + ", " + src2);
                continue;
            }

            size_t eq = raw.find('=');
            if (eq != string::npos) {
                string dst = norm(raw.substr(0, eq));
                string src2 = norm(raw.substr(eq + 1));
                asmLines.push_back("LD " + dst + ", " + src2);
                continue;
            }
        }
        string asmText = "; compiled with --match-rom from C (1:1)\n";
        for (auto& l : asmLines) asmText += l + "\n";
        try {
            writeFile(asmOut, asmText);
        } catch (...) {}
        string outBin = outPath.empty() ? (base + ".bin") : outPath;
        Assembler asm2;
        try {
            asm2.assemble(asmLines);
        } catch (std::exception& e) {
            fprintf(stderr, "assembly error: %s\n", e.what());
            return 1;
        }
        int size = 0x1800;
        outBin = outPath.empty() ? (base + ".bin") : outPath;
        vector<char> buf(size * 2);
        for (int a = 0; a < size; a++) {
            auto it = asm2.words.find(a);
            int w = (it == asm2.words.end()) ? 0xFFF : it->second;
            buf[a * 2] = (char)((w >> 8) & 0xFF);
            buf[a * 2 + 1] = (char)(w & 0xFF);
        }
        std::ofstream f(outBin, std::ios::binary);
        f.write(buf.data(), (std::streamsize)buf.size());
        printf("compiled %d words -> %s (%d words = %d bytes, exact ROM)\n",
               (int)asm2.words.size(), outBin.c_str(), size, (int)buf.size());
        if (!listPath.empty()) {
            std::ofstream lf(listPath);
            for (auto& kv : asm2.words) {
                char tmp[64];
                snprintf(tmp, sizeof(tmp), "0x%04X  0x%03X\n", kv.first, kv.second);
                lf << tmp;
            }
        }
        return 0;
    }

    // Native C-Subset-Erweiterung (typedef/enum/struct/union/sizeof/...):
    // nur aktiv, wenn der Quelltext Erweiterungen verwendet.
    try {
        src = c90::maybe_expand(src);
    } catch (std::exception& e) {
        fprintf(stderr, "compile error: %s\n", e.what());
        return 1;
    }

    vector<string> varInfo;
    string asmText;
    try {
        asmText = compile_c(src, varInfo);
    } catch (std::exception& e) {
        fprintf(stderr, "compile error: %s\n", e.what());
        return 1;
    }
    try {
        writeFile(asmOut, asmText);
    } catch (std::exception& e) {
        fprintf(stderr, "error: %s\n", e.what());
        return 1;
    }
    printf("C -> assembly: %s\n", asmOut.c_str());

    // assemble
    Assembler asm2;
    vector<string> lines;
    {
        std::istringstream ss(asmText);
        string line;
        while (std::getline(ss, line)) lines.push_back(line);
    }
    try {
        asm2.assemble(lines);
    } catch (std::exception& e) {
        fprintf(stderr, "assembly error: %s\n", e.what());
        return 1;
    }
    if (!asm2.labels.count("main")) {
        fprintf(stderr, "error: main() not found\n");
        return 1;
    }
    int mainAddr = asm2.labels["main"];
    if (mainAddr >= 0x1000) {
        fprintf(stderr, "error: main() beyond bank 0\n");
        return 1;
    }
    // main() may now reside in any page of Bank 0 (multi-page code);
    // the reset stub jumps there via PSET. Vectors 0x100-0x10F are
    // omitted from the layout.
    int page = (mainAddr >> 8) & 0xF;
    int step = mainAddr & 0xFF;
    asm2.words[0x100] = 0x002;
    asm2.words[0x102] = 0xE40 | page;
    asm2.words[0x103] = step;
    int top = 0;
    for (auto& kv : asm2.words) top = std::max(top, kv.first);
    int size = std::max(top + 1, 0x200);
    string outBin = outPath.empty() ? (base + ".bin") : outPath;
    {
        vector<char> buf(size * 2);
        for (int a = 0; a < size; a++) {
            auto it = asm2.words.find(a);
            int w = (it == asm2.words.end()) ? 0xFFF : it->second;
            buf[a * 2] = (char)((w >> 8) & 0xFF);
            buf[a * 2 + 1] = (char)(w & 0xFF);
        }
        std::ofstream f(outBin, std::ios::binary);
        f.write(buf.data(), (std::streamsize)buf.size());
    }
    printf("compiled %d words -> %s (%d words, big-endian); main @ 0x%04X "
           "(reset 0x100: JP 0x02 -> PSET 0x%X ; JP 0x%02X)\n",
           (int)asm2.words.size(), outBin.c_str(), size, mainAddr, page, step);
    printf("variables: ");
    for (size_t i = 0; i < varInfo.size(); i++)
        printf("%s%s", i ? ", " : "", varInfo[i].c_str());
    printf("\n");

    if (!listPath.empty()) {
        string lst;
        for (auto& kv : asm2.words) {
            char b[32];
            snprintf(b, sizeof b, "0x%04X  0x%03X\n", kv.first, kv.second);
            lst += b;
        }
        writeFile(listPath, lst);
    }
    return 0;
}
